name: golang-build
on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - run: go build .
